- name: Add rowt-api service to systemd
  become: yes
  copy:
          src: templates/rowt-api.service
          dest: /etc/systemd/system/rowt-api.service
          owner: root
          group: root

- name: Install nginx
  apt:
          name: nginx
          update_cache: yes
          state: present

- name: Add nginx template config for rowt-api
  template:
          src: templates/rowt-api.j2
          dest: /etc/nginx/sites-available/rowt-api
          owner: root
          group: root


- name: Install virtualenv
  apt:
          name: python3-virtualenv
          state: present

- name: Install psycopg2 dependency libpq-dev
  apt: 
          name: libpq-dev
          state: present

- name: Make www directory
  become: yes
  file:
          path: /var/www
          state: directory

- name: Clone API repo
  #become_user: rowt_admin
  become: yes
  git:
          repo: https://gitlab.com/tropicalmentat/rowt-api.git
          dest: /var/www/rowt-api
          update: no

- name: Pip install requirements
  #become_user: rowt_admin
  become: yes
  pip:
          requirements: /var/www/rowt-api/requirements.txt
          virtualenv_command: virtualenv
          virtualenv: /var/www/rowt-api/api-venv

# TODO: Add task for creating gunicorn daemon for project as indicated here: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04
# TODO: Deploy credentials as environmental variables instead of .env
# TODO: Deploy project daemon as service. Use built in service module
# TODO: Configure nginx as reverse proxy for gunicorn
# TODO: Add template file for .env. Think of building .env template using terraform
# https://dev.to/brandonwallace/deploy-flask-the-easy-way-with-gunicorn-and-nginx-jgc
# https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04
