---
- name: Add the user 'rowt_admin' and add it to 'sudo'
  user:
    name: rowt_admin
    group: sudo

- name: Update and upgrade cache
  apt:
          update_cache: yes
          upgrade: yes

- name: Add SSH key to 'rowt_admin'
  authorized_key:
    user: rowt_admin
    state: present
    key: "{{ lookup('file', '/home/$USER/.ssh/id_rsa.pub') }}"

# from https://code-maven.com/enable-ansible-passwordless-sudo
- name: Allow sudo group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set timezone to Asia/Manila
  command: /usr/bin/timedatectl set-timezone Asia/Manila
  become: yes

- name: Reboot
  reboot:
