- name: Restart nginx
  service:
          name: nginx
          state: restarted
  listen: restart nginx

- name: Restart rowt-api service
  service:
          name: rowt-api
          state: restarted
  listen: restart rowt-api
