- name: Install php-cgi
  become: yes
  apt:
          name: php-cgi
          state: present
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"

- name: Install nominatim required packages
  become: yes
  apt:
          name: [
                  build-essential,cmake,g++,libboost-dev,libboost-system-dev,
                  libboost-filesystem-dev,libexpat1-dev,zlib1g-dev,
                  libbz2-dev,libpq-dev,libproj-dev,
                  postgresql-server-dev-12,postgresql-12-postgis-3,
                  postgresql-contrib-12,postgresql-12-postgis-3-scripts,
                  php,php-pgsql,php-intl,libicu-dev,python3-dotenv,
                  python3-psycopg2,python3-psutil,python3-jinja2,python3-icu
                ]
          state: present
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"


- name: Uncompress Nominatim binaries
  unarchive:
          owner: rowt_admin
          group: sudo
          src: https://nominatim.org/release/Nominatim-3.7.2.tar.bz2
          dest: /home/rowt_admin/
          remote_src: yes
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"


- name: Make build directory for Nominatim
  file:
          path: /home/rowt_admin/build
          state: directory
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"


- name: Cmake
  shell: cmake /home/rowt_admin/Nominatim-3.7.2
  become: yes
  become_user: rowt_admin
  args:
          chdir: /home/rowt_admin/build
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"


- name: Make
  become: yes
  shell: make
  args:
          chdir: /home/rowt_admin/build
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"


- name: Make install
  become: yes
  shell: make install
  args:
          chdir: /home/rowt_admin/build
  when: "'db' in inventory_hostname or 'api' in inventory_hostname"

- name: Make directory for website
  file:
          path: /home/rowt_admin/nominatim-ph
          state: directory
  when: "'db' in inventory_hostname"


- name: Load data
  shell: 
        cmd: nominatim import --osm-file ../philippines-latest.osm.pbf -v 2>&1 | tee setup.log 
        chdir: /home/rowt_admin/nominatim-ph
  async: 200000
  poll: 0
  when: "'db' in inventory_hostname"
