# https://computingforgeeks.com/how-to-install-postgis-on-ubuntu-debian/
- name: Update and install upgrades
  apt:
          upgrade: safe
          state: present

#only need it when configuring the first time
- name: Reboot
  reboot: 

- name: Install gnupg2 
  apt: 
          state: present
          name: gnupg2

- name: Download apt key for postgres 
  get_url: 
          url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
          dest: /home/rowt_admin/

- name: Add apt key
  apt_key:
          url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
          state: present

- name: Add postgres apt repo
  apt_repository:
          repo: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main

- name: Set-up postgres
  apt: 
          name: [postgresql-12,postgresql-client-12]
          state: present

- name: Set-up postgis-3
  apt: 
          name: [postgis,postgresql-12-postgis-3]

- name: Set-up python dependencies 
  apt: 
          name: [python3-pip,python3-dev,libpq-dev] 
          state: present

- name: Check if psycopg2 is installed
  pip:
          name: psycopg2
          state: present

#https://stackoverflow.com/questions/25751085/postgresql-failing-peer-authentication-with-ansible
- name: Install setfacl support
  become: yes
  apt: pkg=acl

- name: Set password for postgres
  become: yes
  become_user: postgres
  postgresql_user:
          name: postgres
          password: 'test123'

- name: Create rowt_admin db user
  become: yes
  become_user: postgres
  postgresql_user:
          name: rowt_admin
          password: test#124$
          role_attr_flags: CREATEDB,SUPERUSER

- name: Create rowt_db
  become_user: rowt_admin
  postgresql_db:
          login_user: rowt_admin
          login_password: test#124$
          name: rowt_db
          owner: rowt_admin

- name: Enable postgis extension in rowt_db
  become_user: rowt_admin
  postgresql_query: 
          login_user: rowt_admin 
          login_password: test#124$
          db: rowt_db
          query: CREATE EXTENSION postgis
  ignore_errors: True

# convert this into handler
- name: Check postgis version
  become_user: rowt_admin 
  postgresql_query: 
          login_user: rowt_admin 
          login_password: test#124$
          db: rowt_db
          query: SELECT PostGIS_version()
  register: result

- debug:
        var: result 

- name: Enable hstore extension in rowt_db
  become_user: rowt_admin
  postgresql_query: 
          login_user: rowt_admin 
          login_password: test#124$
          db: rowt_db
          query: CREATE EXTENSION hstore 
  ignore_errors: True

- name: Install osm2pgsql
  apt:
          name: osm2pgsql
          state: present

- name: Download latest philippine data
  get_url:
          url: https://download.geofabrik.de/asia/philippines-latest.osm.pbf
          dest: /home/rowt_admin/philippines-latest.osm.pbf
          force: no
  

- name: Load data into rowt_db
  become_user: rowt_admin
  command: osm2pgsql -d rowt_db -j -c -C=1200 -s philippines-latest.osm.pbf 
  async: 100000
  poll: 0
  register: load

- debug:
        var: load 

