# https://computingforgeeks.com/how-to-install-postgis-on-ubuntu-debian/
- name: Update and install upgrades
  apt:
          update_cache: yes
          upgrade: safe
          state: present

# only need it when configuring the first time
#- name: Reboot
#  reboot: 

- name: Install gnupg2
  apt:
          state: present
          name: gnupg2

- name: Download apt key for postgres 
  get_url: 
          url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
          dest: /home/rowt_admin/

- name: Add apt key
  apt_key:
          url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
          state: present

- name: Add postgres apt repo
  apt_repository:
          repo: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main

- name: Set-up postgres
  apt: 
          name: [postgresql-12,postgresql-client-12]
          state: present

- name: Set-up postgis-3
  apt: 
          name: [postgis,postgresql-12-postgis-3]

- name: Set-up python dependencies 
  apt:
          name: [python3-pip,python3-dev,libpq-dev]
          state: present

- name: Check if psycopg2 is installed
  pip:
          name: psycopg2
          state: present

#https://stackoverflow.com/questions/25751085/postgresql-failing-peer-authentication-with-ansible
- name: Install setfacl support
  become: yes
  apt: pkg=acl

- name: Set password for postgres
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
          name: postgres
          password: 'test123'
